name: Railway Scheduled Start/Stop

on:
  schedule:
    - cron: "0 12 * * *"   # Włącz o 12:00 UTC
    - cron: "0 13 * * *"   # Wyłącz o 13:00 UTC
  workflow_dispatch:       # Pozwala uruchomić ręcznie

jobs:
  control:
    runs-on: ubuntu-latest
    steps:
      - name: Włącz/Wyłącz Railway
        run: |
          if [ "$(date -u +%H)" = "12" ]; then
            echo "==> START Railway"
            curl -X POST https://backboard.railway.app/project/YOUR_PROJECT_ID/service/YOUR_SERVICE_ID/deploy \
              -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}"
          elif [ "$(date -u +%H)" = "13" ]; then
            echo "==> STOP Railway"
            curl -X DELETE https://backboard.railway.app/project/YOUR_PROJECT_ID/service/YOUR_SERVICE_ID/instances \
              -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}"
          fi
