name: Railway Scheduled Start/Stop

on:
  schedule:
    - cron: "00 12 * * *"    # codziennie o 08:30 UTC
    - cron: "00 13 * * *"    # codziennie o 00:30 UTC
  workflow_dispatch:

jobs:
  start_bot:
    if: github.event.schedule == '30 8 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Start Railway Project
        run: |
          curl -X POST https://backboard.railway.app/api/v1/projects/${{ secrets.RAILWAY_PROJECT_ID }}/deployments \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"clearCache":true}'

  stop_bot:
    if: github.event.schedule == '30 0 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Stop Railway Project
        run: |
          curl -X POST https://backboard.railway.app/api/v1/projects/${{ secrets.RAILWAY_PROJECT_ID }}/services/stop \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_KEY }}" \
          -H "Content-Type: application/json"
