name: Railway Scheduled Start/Stop

on:
  schedule:
    - cron: "00 12 * * *"    # o 00:30 UTC – wyłącz
    - cron: "00 13 * * *"    # o 08:30 UTC – włącz
  workflow_dispatch:

jobs:
  control_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Decyzja: start czy stop?
        run: |
          HOUR=$(date -u +"%H")
          MINUTE=$(date -u +"%M")
          echo "Godzina UTC: $HOUR:$MINUTE"

          if [ "$HOUR" = "08" ] && [ "$MINUTE" = "30" ]; then
            echo "Włączam Railway..."
            curl -X POST https://backboard.railway.app/api/v1/projects/${{ secrets.RAILWAY_PROJECT_ID }}/deployments \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache":true}'
          elif [ "$HOUR" = "00" ] && [ "$MINUTE" = "30" ]; then
            echo "Wyłączam Railway..."
            curl -X POST https://backboard.railway.app/api/v1/projects/${{ secrets.RAILWAY_PROJECT_ID }}/services/stop \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_API_KEY }}" \
            -H "Content-Type: application/json"
          else
            echo "Nie wykonano żadnej akcji."
          fi
