name: Stop Railway Services

on:
  schedule:
    - cron: "25 9 * * *"
  workflow_dispatch:

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Stop Bot Service
        run: |
          curl -X POST https://backboard.railway.app/api/v1/projects/${{ secrets.RAILWAY_PROJECT_ID }}/services/${{ secrets.RAILWAY_SERVICE_ID }}/stop \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_KEY }}" \
          -H "Content-Type: application/json"

      - name: Stop DB Service
        run: |
          curl -X POST https://backboard.railway.app/api/v1/projects/${{ secrets.RAILWAY_PROJECT_ID }}/services/${{ secrets.RAILWAY_DB_SERVICE_ID }}/stop \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_KEY }}" \
          -H "Content-Type: application/json"
