name: Stop Railway Services

on:
  schedule:
    - cron: "31 9 * * *"
  workflow_dispatch:

jobs:
  stop:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROJECT_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Link project
        run: railway link --project f241eb99-c0cd-43d0-b052-ed4bc09ab72a

      - name: Stop all services in project
        run: railway down
